name: Website
id: website
stages:
  - id: build
    base: node:lts
    singlelayer: false
    labels:
      maintainer: Vanilla OS Contributors
    cmd: ["sh", "-c", "cd /app && pnpm generate-articles && pnpm dev"]
    expose:
      "6080": ""
    modules:
      - name: init
        type: shell
        source:
          type: git
          url: https://github.com/Vanilla-OS/website
          branch: v2
          commit: latest
        commands:
          - mv /sources/init /app

      - name: pnpm
        type: shell
        commands:
          - corepack enable pnpm
          - corepack use pnpm@latest

      - name: build
        type: shell
        commands:
          - cd /app
          - pnpm install
